events { worker_connections 1024; }

http {
    upstream user_service    { server user-service:8000; }
    upstream product_service { server product-service:8000; }
    upstream order_service   { server order-service:8000; }
    upstream payment_service { server payment-service:8000; }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }
        location /api/token/ {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
        }
        location /api/products/ {
            proxy_pass http://product_service;
            proxy_set_header Host $host;
        }
        location /media/ {
            proxy_pass http://product_service;
            proxy_set_header Host $host;
        }
        location /api/orders/ {
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }
        location /api/payment/ {
            proxy_pass http://payment_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
